// <auto-generated />
namespace Vidly_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview5-19254-05")]
    public sealed partial class testRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201906212255471_testRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
